/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bonus;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;
import java.util.Vector;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
//import static query.DesignForm.sohang;

/**
 *
 * @author Tuyet Anh
 */
public class Manageproduct extends javax.swing.JFrame {
    Vector head = new Vector();
    Vector data = new Vector();
    private static String accountidd ;
    public static String same = "true";
    public String getaccountid(){
        return accountidd;
    }
    public void setaccountid(String id){
        this.accountidd = id;
    }

    /**
     * Creates new form Manageproduct
     */
    public Manageproduct(String id) {
        this.accountidd = id;
        this.setLocationRelativeTo(null);
        initComponents();
        head.add("ID");
        head.add("Name");
        head.add("Type");
        head.add("Quantity");
        head.add("Material");
        head.add("Price");
        head.add("Condition");
        String connectionUr1 = "jdbc:sqlserver://localhost:1433;databaseName=FinalSourceDatabase;user=sa;password=123456789;encrypt=false";
        try (Connection con = DriverManager.getConnection(connectionUr1);
            Statement stmt = (Statement) con.createStatement();){
            String SQL = "Select P.Product1ID, P.Product1Name, P.ProductType, P.Quantity, P.Material, P.Price, P.Condition From Product1 as P, Employees as E Where P.EmpID = E.EmpID AND E.AccountID = '"+accountidd+"'";
            System.out.println("Successfull");
            ResultSet rs = stmt.executeQuery(SQL);

            ResultSetMetaData metaData = rs.getMetaData();
            int numberOfColumns = metaData.getColumnCount();

            while (rs.next()){
                Vector v = new Vector();
                for (int i = 1; i<= numberOfColumns;i++){
                    v.add(rs.getObject(i));

                }
                data.add(v);
   
            }
        }
        catch (SQLException e){
               JOptionPane.showConfirmDialog(this, "Failed connect");
        }
        
        jTable1.setModel(new DefaultTableModel(data, head));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashboard = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnadd = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        txtname = new javax.swing.JTextField();
        txtcondition = new javax.swing.JTextField();
        txttype = new javax.swing.JTextField();
        txtprice = new javax.swing.JTextField();
        txtquantity = new javax.swing.JTextField();
        txtmaterial = new javax.swing.JTextField();
        dashboard1 = new javax.swing.JLabel();
        txtcondition1 = new javax.swing.JTextField();
        txtmaterial1 = new javax.swing.JTextField();
        comback = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dashboard.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        dashboard.setForeground(new java.awt.Color(0, 51, 153));
        dashboard.setText("Product management");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Type", "Condition", "Material", "Price", "Quantity", "CusID"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Product Name:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Product Type:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Condition:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Material: ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Price:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Quantity:");

        btnadd.setBackground(new java.awt.Color(0, 102, 102));
        btnadd.setForeground(new java.awt.Color(255, 255, 255));
        btnadd.setText("Add");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btndelete.setBackground(new java.awt.Color(0, 102, 102));
        btndelete.setForeground(new java.awt.Color(255, 255, 255));
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnupdate.setBackground(new java.awt.Color(0, 102, 102));
        btnupdate.setForeground(new java.awt.Color(255, 255, 255));
        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btnclear.setBackground(new java.awt.Color(0, 102, 102));
        btnclear.setForeground(new java.awt.Color(255, 255, 255));
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });

        txtcondition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtconditionActionPerformed(evt);
            }
        });

        txttype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttypeActionPerformed(evt);
            }
        });

        txtprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpriceActionPerformed(evt);
            }
        });

        txtquantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtquantityActionPerformed(evt);
            }
        });

        txtmaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmaterialActionPerformed(evt);
            }
        });

        dashboard1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        dashboard1.setForeground(new java.awt.Color(0, 51, 153));
        dashboard1.setText("Product List");

        txtcondition1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcondition1ActionPerformed(evt);
            }
        });

        txtmaterial1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmaterial1ActionPerformed(evt);
            }
        });

        comback.setText("Back to dash board ");
        comback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(dashboard1)
                .addGap(0, 379, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtcondition, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txttype, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtprice, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtquantity, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtmaterial, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtcondition1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtmaterial1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtname, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comback)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnclear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btndelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnupdate)))))
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(dashboard))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel4, jLabel5, jLabel7});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dashboard1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dashboard)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(txttype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(txtcondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtcondition1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtmaterial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtmaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtquantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnadd)
                            .addComponent(btnclear)
                            .addComponent(btndelete)
                            .addComponent(btnupdate))
                        .addGap(18, 18, 18)
                        .addComponent(comback)
                        .addGap(2, 2, 2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7});

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private static final String alpha = "abcdefghijklmnopqrstuvwxyz"; // a-z     
    private static final String alphaUpperCase = alpha.toUpperCase(); // A-Z     
    private static final String digits = "0123456789"; // 0-9     
    private static final String ALPHA_NUMERIC = alphaUpperCase + digits;
    private static final Random generator = new Random(); /**
             * * Random string with a-zA-Z0-9, not included special characters
             */
    public static int randomNumber(int min, int max) {         return generator.nextInt((max - min) + 1) + min;}

    public static String randomAlphaNumeric() {
        int numberOfCharactor = 6;
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < numberOfCharactor; i++) {
            int number = randomNumber(0, ALPHA_NUMERIC.length() - 1);
            char ch = ALPHA_NUMERIC.charAt(number);
            sb.append(ch);
        }
        return sb.toString();
    }
    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        int n = jTable1.getSelectedRow();
        String a = data.get(n).toString();
        data.remove(n);
        a= a.replace("[", "");
        a= a.replace("]", "");
        String [] group = a.split(",");
        String id = group[0];
        System.out.println(group);

        Vector t = new Vector();
        t.add(group[0]);

         
        String connectionUr1 = "jdbc:sqlserver://localhost:1433;databaseName=FinalSourceDatabase;user=sa;password=123456789;encrypt=false";
        try {
            Connection con = DriverManager.getConnection(connectionUr1);

                if(txtname.getText().equals("")){
                t.add(group[1]);
                }
                else{ 
                    String sql = "UPDATE Product1 SET Product1Name = ? WHERE Product1ID = ? ";
                    PreparedStatement ps = con.prepareStatement(sql);
                    ps.setString(1,txtname.getText() );
                    ps.setString(2, id);
                    ps.execute();
                    t.add(txtname.getText());
                }
            
            if(txttype.getText().equals("")){
                t.add(group[2]);
            }
            else { 
                String sql = "UPDATE Product1 SET ProductType = ? WHERE Product1ID = ? ";
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setString(1,txttype.getText() );
                ps.setString(2,id );
                ps.execute();
                t.add(txttype.getText());
            }
            
            if(txtquantity.getText().equals("")){
                t.add(group[3]);
            }
             else {
                String sql = "UPDATE Product1 SET Quantity = ? WHERE Product1ID = ? ";
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setString(1, txtquantity.getText());
                ps.setString(2,id );
                ps.execute();
                t.add(txtquantity.getText());
            }
            
            if(txtmaterial1.getText().equals("")){
                t.add(group[4]);
            }
            else { 
                String sql = "UPDATE Product1 SET Material = ? WHERE Product1ID = ? ";
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setString(1, txtmaterial1.getText());
                ps.setString(2,id );
                ps.execute();
                t.add(txtmaterial1.getText());
            }
             
            
            if(txtprice.getText().equals("")){
                t.add(group[5]);
            }
            else { 
                String sql = "UPDATE Product1 SET Price = ? WHERE Product1ID = ? ";
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setDouble(1, Double.parseDouble(txtprice.getText()));
                ps.setString(2,id );
                ps.execute();
                 t.add(txtprice.getText());
            }
            
            if (txtcondition1.getText().equals("")){
                t.add(group[6]);
            }
            else { 
                String sql = "UPDATE Product1 SET Condition = ? WHERE Product1ID = ? ";
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setString(1, txtcondition1.getText());
                ps.setString(2,id );
                System.out.println(ps);
                ps.execute();
                t.add(txtcondition1.getText());
            }
            System.out.println(t.toString());
            System.out.println("HAAAAAAAA");
            data.add(t);
            jTable1.setModel(new DefaultTableModel(data, head));
           
                
            
        } catch (Exception e){
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        
        txtname.setText("");
        txttype.setText("");
        txtcondition1.setText("");
        txtmaterial1.setText("");
        txtprice.setText("");
        txtquantity.setText("");

        
        
    }//GEN-LAST:event_btnclearActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        int n = jTable1.getSelectedRow();
        // data {[a,d,c], [b,c,s]}
        // data.get(n) = [a,b,c]
        String a = data.get(n).toString(); // a = "[a,b,c]"
        a= a.replace("[", "");         // a = "a,b,c"
        a= a.replace("]", ""); 
        String [] group = a.split(","); // group = [a,b,c]
        String id = group[0];
        
        data.remove(n);
        jTable1.setModel(new DefaultTableModel(data, head));
        String connectionUr1 = "jdbc:sqlserver://localhost:1433;databaseName=FinalSourceDatabase;user=sa;password=123456789;encrypt=false";
        try {
            Connection con = DriverManager.getConnection(connectionUr1);
        
            String sql = "DELETE  FROM Product1 WHERE Product1ID = ? ";
            PreparedStatement ps1 = con.prepareStatement(sql);
                ps1.setString(1,id );
                
                ps1.execute();
        } catch (Exception e){
            e.printStackTrace();
        }
        JOptionPane.showMessageDialog(this, "Delete Successful");
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:

                String connectionUr1 = "jdbc:sqlserver://localhost:1433;databaseName=FinalSourceDatabase;user=sa;password=123456789;encrypt=false";
        try {
            Connection con = DriverManager.getConnection(connectionUr1);
            System.out.println("Connect");
            String product1ID = "HAHA";
        
            while (same.equals("true")){
                product1ID = Manageproduct.randomAlphaNumeric();
                Statement s = (Statement) con.createStatement();
                String sql = "Select * From Product1 where Product1ID = '"+product1ID+"';";
                ResultSet re = s.executeQuery(sql);
                if(re.next()){
                    same="true";
                }
                else{
                    same = "false";
                }

                }
            
            if (txtname.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Name is Required.");
            }
            else if (txttype.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Type is Required.");
            }
            else if (txtcondition1.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Condition is Required.");
            }
            else if (txtmaterial1.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Material is Required.");
            }
            else if (txtprice.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Price is Required.");
            }
            else if (txtquantity.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Quantity is Required.");
            }
            else {
                Statement s = (Statement) con.createStatement();
                String sql = "Select EmpID, AdminID From Employees where AccountID = '"+accountidd+"'; ";
                System.out.println(sql);
                 

                ResultSet re = s.executeQuery(sql);
                StringBuilder results = new StringBuilder();
                ResultSetMetaData metaData = re.getMetaData();
                int numberOfColumns = metaData.getColumnCount();
                String EmpID = "A";
                String AdminID= "A";

                while (re.next()){
                for (int i = 1; i<= numberOfColumns;i++){
                    results.append (re.getObject(i)).append(",");
                }
                String str = results.toString();
                String [] words = str.split(",");
                EmpID = words[0];
                AdminID = words[1];
               
            }
               System.out.println(EmpID); 
               System.out.println(AdminID);
               String sql1 = "Insert into Product1 ( Product1ID, Product1Name, ProductType, Quantity, Material, Price, Condition, EmpID, AdminID) VALUES(?, ?, ?, ?, ?, ?,?,?,?)";
                PreparedStatement ps1 = con.prepareStatement(sql1);
                ps1.setString(1,Manageproduct.randomAlphaNumeric());
                ps1.setString(2, txtname.getText());
                ps1.setString(3, txttype.getText());
                ps1.setString(4, txtquantity.getText());
                ps1.setDouble(7, Double.parseDouble(txtcondition1.getText()));
                ps1.setDouble(6, Double.parseDouble(txtprice.getText()));
                ps1.setString(5, txtmaterial1.getText());
                ps1.setString(8, EmpID);
                ps1.setString(9, AdminID);
                
                ps1.execute();
                
                Vector add = new Vector();
                add.add(product1ID);
                add.add(txtname.getText());
                add.add(txttype.getText());
                add.add(txtquantity.getText());
                add.add(txtmaterial1.getText());
                add.add(Double.parseDouble(txtprice.getText()));
                add.add(Double.parseDouble(txtcondition1.getText()));
                data.add(add);
                jTable1.setModel(new DefaultTableModel(data, head));
                
                
                
            }
  
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null,"Add Successfully");
        e.printStackTrace();
        }

        
    }//GEN-LAST:event_btnaddActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtconditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtconditionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconditionActionPerformed

    private void txttypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttypeActionPerformed

    private void txtpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpriceActionPerformed

    private void txtquantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtquantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtquantityActionPerformed

    private void txtmaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmaterialActionPerformed

    private void txtcondition1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcondition1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcondition1ActionPerformed

    private void txtmaterial1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmaterial1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmaterial1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        displaydetails(((JTable) evt.getSource()).getSelectedRow());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        // TODO add your handling code here:
        displaydetails(((JTable) evt.getSource()).getSelectedRow());
    }//GEN-LAST:event_jTable1KeyReleased

    private void combackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combackMouseClicked
        // TODO add your handling code here:
        Employeesinterface e = new Employeesinterface(accountidd);
        e.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_combackMouseClicked
    private void displaydetails (int selectedRows){
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manageproduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manageproduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manageproduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manageproduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manageproduct(accountidd).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel comback;
    private javax.swing.JLabel dashboard;
    private javax.swing.JLabel dashboard1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtcondition;
    private javax.swing.JTextField txtcondition1;
    private javax.swing.JTextField txtmaterial;
    private javax.swing.JTextField txtmaterial1;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtquantity;
    private javax.swing.JTextField txttype;
    // End of variables declaration//GEN-END:variables
}
